### ISSUE TITLE
Is it possible to get data pipeline codebase?

### ISSUE THREAD

**Issue by jun297** [IDEA-Research/Motion-X#1]
Hi, thanks for this nice work
I am interested in getting more pose from video, can I access to the pipeline codebase for motionX?

**Comment by foocker** [comment]
> Hi, thanks for this nice work I am interested in getting more pose from video, can I access to the pipeline codebase for motionX?

数据看起来抖动明显？是质量问题？

**Comment by andrewnc** [comment]
I would also be interested in learning more about the data pipeline, are there plans to open source that portion of the project?

**Comment by linjing7** [comment]
@jun297 @andrewnc  Hi, thanks for your interest! 
Currently, we plan to release the dataset in September. We are keeping improving our data annotation pipeline to achieve more robust and accurate results. We would consider open-sourcing the code in the future.

**Comment by linjing7** [comment]
@foocker Thanks for your advice. We have improved our annotation pipeline and now the jitter is obviously decreased. You can see more examples on our [website](https://motion-x-dataset.github.io/).

**Comment by jun297** [comment]
Thank you for the reply.
I am looking forward to the release.

**Comment by baitian752** [comment]
@linjing7 Hi linjing, I am looking for some methods to smooth my smpl pose of 3d pose estimation. I see this repo has the best visual result. Can you share the current codebase?
