### ISSUE TITLE
AIST motions error

### ISSUE THREAD

**Issue by sohananisetty** [IDEA-Research/Motion-X#10]
Hi! When I try to visualize AIST motions they appear to have some problem. In my custom visualizer the other motion dataset appear like this: (In this example from GRAB)
![grab](https://github.com/IDEA-Research/Motion-X/assets/113209814/47340ff5-e52c-41f6-8e2d-6ec06577af10)

But the AIST motions appear like this:
![aist](https://github.com/IDEA-Research/Motion-X/assets/113209814/7d038f7f-43e1-4a17-b610-c7a06709ed25)

Can you please recheck the aist motions?

**Comment by linjing7** [comment]
Hi, which motion clip do you visualize?

**Comment by sohananisetty** [comment]
aist/subset_0000/Dance_Break_3_Step_clip_1.npy and aist/subset_0000/Dance_Break_3_Step.npy. But this was the case with other aist moions too

**Comment by linjing7** [comment]
Hi, we found the problem. AIST is the multi-view dataset and we need to rescale the translation. We perform the rescaling operation in our visualization and training dataloader. We have added this processing script in the latest commit. Please pull the latest code and refer to this [instruction](https://github.com/IDEA-Research/Motion-X/tree/main/non-mocap-dataset-process). Sorry for the mistake.

**Comment by sohananisetty** [comment]
Thanks. Works now

**Comment by Run542968** [comment]
Hi, @sohananisetty.
May I ask where you got the AIST dataset from, the latest download link lacks AIST content (both motion and text).
Looking forward your reply!
