### ISSUE TITLE
Can you share the processing code to convert Motion-X to your Tomato representation

### ISSUE THREAD

**Issue by sohananisetty** [IDEA-Research/Motion-X#12]
Is it possible for you to release the preprocessing portion to convert the SMPL representation to the representation used in your tomato paper?

**Comment by LinghaoChan** [comment]
Hi @sohananisetty ,

@shunlinlu and @LinghaoChan have provided a tutorial on how to get the tomato representations you want. Please refer to the [code](https://github.com/IDEA-Research/HumanTOMATO/tree/main/src/tomato_represenation).

**Comment by LinghaoChan** [comment]
@sohananisetty We also update the code [here](https://github.com/IDEA-Research/Motion-X/tree/main/tomato_represenation).
