### ISSUE TITLE
What is face shape?

### ISSUE THREAD

**Issue by mingdianliu** [IDEA-Research/Motion-X#16]
Hi, just want to know what is the meaning of face shape (100-dim) in the data preprocessing scripts? Thanks.

**Comment by linjing7** [comment]
Hi, it's a parameter related to the face appearance (e.g., round face, long face, etc). We do not use it in our motion representation, but we still provide it as it may help in some scenes that require both motion and appearance information.

**Comment by mingdianliu** [comment]
Thanks for your quick response!
