### ISSUE TITLE
The whole-body pose description

### ISSUE THREAD

**Issue by jiayoujiayoujiayoua** [IDEA-Research/Motion-X#19]
Thanks for sharing your excellent work. I would like to follow your works, but the sequence-level semantic labels is unsatisfactory in some subsets of Motion-X. I'm wondering if you could release whole-body pose description.

**Comment by linjing7** [comment]
Hi, thanks for your interest.  We are trying to improve our semantic labels. We will release the improved semantic labels and pose description in the near future.
