### ISSUE TITLE
Which dataset to download for EgoBody

### ISSUE THREAD

**Issue by marybloodyzz** [IDEA-Research/Motion-X#20]
<img width="448" alt="image" src="https://github.com/IDEA-Research/Motion-X/assets/112670928/175590f7-c061-4d8d-ae33-4f7dd5eb70aa">
For the list of files which one should be downloaded as the EgoBody dataset mentioned in the repo?

**Comment by linjing7** [comment]
Hi, please download the following files:
<img width="510" alt="image" src="https://github.com/IDEA-Research/Motion-X/assets/70081899/5525abbd-e5d4-4be0-8c01-338a2888ddf6">

**Comment by ellemcfarlane** [comment]
Also, fyi for other people, you can figure out which subsets you need for each of these datasets by looking at [Data preparing section](https://github.com/IDEA-Research/Motion-X/tree/main/mocap-dataset-process#1-data-preparing) and clicking arrows for e.g. "Download AMASS motions for Humanml3D."
