### ISSUE TITLE
Motion-X To HumanML3D

### ISSUE THREAD

**Issue by fluide1022** [IDEA-Research/Motion-X#21]
Excellent Work！How can the Motion-X transfer to HumanMl3D format

**Comment by Nauw1010** [comment]
Need help as well! Thank you!

**Comment by fyyakaxyy** [comment]
+1，plz！

**Comment by LinghaoChan** [comment]
@fluide1022 @Nauw1010 @fyyakaxyy Thanks for the interest! 

HumanTOMATO supports the tomato format data format for training on Motion-X. The tomato format is extended from the H3D Format and is not the same as the H3D format. Please refer to [HumanTOMATO repo](https://github.com/IDEA-Research/HumanTOMATO/tree/main/src/tomato_represenation). For detailed ablation on motion representation design choice, please refer to Appendix B.1 in the [paper](https://arxiv.org/pdf/2310.12978.pdf).

**Comment by shunlinlu** [comment]
@fluide1022 @Nauw1010 @fyyakaxyy 

If you are looking for some converting code, I've prepared them for you. please check the folder motionx2humanml and follow the instruction in README.

**Comment by fyyakaxyy** [comment]
> @fluide1022 @Nauw1010 @fyyakaxyy Thanks for the interest!
> 
> HumanTOMATO supports the tomato format data format for training on Motion-X. The tomato format is extended from the H3D Format and is not the same as the H3D format. Please refer to [HumanTOMATO repo](https://github.com/IDEA-Research/HumanTOMATO/tree/main/src/tomato_represenation). For detailed ablation on motion representation design choice, please refer to Appendix B.1 in the [paper](https://arxiv.org/pdf/2310.12978.pdf).

Thanks，I try to convert Motion-X to HumanML3D.
The pipline is: MotionX-->AMASS-->HumanML3D, but it seems that some parameters are missing, resulting in the lack of some motion features in the bone animation. Some results:
https://github.com/fyyakaxyy/animationGPT/blob/main/dataset/dataset.md

**Comment by fyyakaxyy** [comment]
> @fluide1022 @Nauw1010 @fyyakaxyy
> 
> If you are looking for some converting code, I've prepared them for you. please check the folder motionx2humanml and follow the instruction in README.

Thank you! Could you provide a link?

**Comment by shunlinlu** [comment]
here it is. [transfer_to_body_only_humanml](https://github.com/IDEA-Research/Motion-X/blob/main/tomato_represenation/motionx2humanml/transfer_to_body_only_humanml.py)

**Comment by fyyakaxyy** [comment]
> here it is. [transfer_to_body_only_humanml](https://github.com/IDEA-Research/Motion-X/blob/main/tomato_represenation/motionx2humanml/transfer_to_body_only_humanml.py)

thanks！
