### ISSUE TITLE
plot_3d_global.py无法运行

### ISSUE THREAD

**Issue by Wolverhampton0** [IDEA-Research/Motion-X#23]
请问plot_3d_global.py的final data是通过什么步骤产生的？
另外这个example对象是什么，在哪里定义的？
谢谢。
`Traceback (most recent call last):
  File "/app/Motion-X-main/Motion-X-main/tomato_represenation/plot_3d_global.py", line 362, in <module>
    joints = np.load(example)
NameError: name 'example' is not defined`

**Comment by shunlinlu** [comment]
Hi, @Wolverhampton0 

The input shape of plot_3d_global should be b×frame×52×3, which is the joint representation. You could change the input example path to your own. More info can be found in REAMDE. 

Shunlin

**Comment by shunlinlu** [comment]
It is actually the file or the joints you wanna visualize. Please check the comments on it.
