### ISSUE TITLE
"AttributeError: can't set attribute" of plot_feature.py

### ISSUE THREAD

**Issue by yyvhang** [IDEA-Research/Motion-X#28]
Hi, when I run the plot_feature.py, line151-->'ax.lines = []' arises the error: AttributeError: can't set attribute. Is it due to the version of mpl_toolkits? How can I solve it, many thanks for your response!

**Comment by mengqing0312** [comment]
你好，我也遇到了这个问题。降低matplotlib为3.3.1可以运行。运行plot_feature.py没有报错，但是plot_3d_global.py中有报错，把auto_add_to_figure=False去掉后可以出结果。下面分别是GRAB/s10/airplane_fly_1.npy这个序列plot_3d_global、plot_feature的结果。为什么看起来浮动很严重呢，请问你也是这样的吗。谢谢回答。
![output](https://github.com/IDEA-Research/Motion-X/assets/121235781/d10113b4-f984-479e-88d5-64d7f8305042)
![outputfeature](https://github.com/IDEA-Research/Motion-X/assets/121235781/5286a1a5-ee8f-43c5-8b9c-37ce196c9ed0)

**Comment by jayze3736** [comment]
@mengqing0312 Hello, Have you resolved the problem? I am also having a same situation with you which the person appears to be suspended in mid-air. Could this be related to a problem with the preprocessing code?

**Comment by PerfectBlueFeynman** [comment]
@yyvhang @jayze3736 Try matplotlib version 3.4.1, it solves my problem.
