### ISSUE TITLE
About tomato representation

### ISSUE THREAD

**Issue by aekx** [IDEA-Research/Motion-X#32]
Hi, thanks for your great job!
I tried to run the code in the tomato representation, but it seems there are other tasks to be done before that?And I wonder that what environment setting is needed to obtain tomato representation and use body-only motion?

**Comment by linjing7** [comment]
Hi, thanks for your interest. I think the environment we needed for data preprocessing is quite simple, e.g., smplx. But you can follow this [repo](https://github.com/EricGuo5513/HumanML3D) to establish a full environment for future research.
