### ISSUE TITLE
Significant Errors! Some data are all zero T-Poses

### ISSUE THREAD

**Issue by kevsak5** [IDEA-Research/Motion-X#36]
a lot of clips in fitness and idea400 have all zero body poses:
![smplx_322_idea400_subset_0013_Simultaneously_Drink_Water_And_Sitting](https://github.com/IDEA-Research/Motion-X/assets/153256607/a70fd2e6-e01f-463c-94ef-4b190604c34c)

Could you please comment if a fix is available? Thanks.

**Comment by kevsak5** [comment]
this is confirmed by the official rendering as well: https://deepdataspace.com/dataset/motionx/visualization%2Ffitness%2Fsubset_0101.json?pageState=%7B%22page%22%3A1%2C%22previewIndex%22%3A-1%7D

**Comment by linjing7** [comment]
Hi, thanks for your interest. There are several subsets that we have not manually checked and I guess these failure cases exist in a certain subset. We will manually checked these subsets and update the labels soon.

**Comment by kevsak5** [comment]
thanks for the prompt response.
The problematic subsets are:
fitness subset 93, 101, 106
idea400 subset 13
Hope that this helps.

**Comment by linjing7** [comment]
Okay, thanks for your information!
