### ISSUE TITLE
about the text descriptions (text_v1.1) augmented by Vicuna 1.5 

### ISSUE THREAD

**Issue by jiayoujiayoujiayoua** [IDEA-Research/Motion-X#38]
Thank you very much for uploading the text descriptions augmented by Vicuna 1.5. However, it seems that these descriptions are not significantly different from the previous ones, and the modification date of the files is also October 24, 2023. I wonder if you might have uploaded the wrong files?

**Comment by linjing7** [comment]
Thanks for your interest! We have updated the [downloading link](https://drive.google.com/file/d/1DecnWjxM7d2uQKaHk_u5QQRALlNle_q_/view?usp=sharing).

**Comment by jiayoujiayoujiayoua** [comment]
thanks
