### ISSUE TITLE
Has the data been released?

### ISSUE THREAD

**Issue by liqimai** [IDEA-Research/Motion-X#4]
Great job! This dataset is like the ImageNet for the 3D motion! It's definitely going to significantly boost performance on various motion-related tasks!

I noticed that you plan to release Motion-X by Sept. 2023. As of now, I can not find somewhere to access the data. Could you please hint me whether the dataset is released or not?

**Comment by linjing7** [comment]
Hi, thanks for your interest! We are manually checking our labels to ensure the quality. We plan to release the data in late September or early October.

**Comment by liqimai** [comment]
Thanks! Look forward to it!

**Comment by prinshul** [comment]
@linjing7 can you share data/preprocessing scripts and baseline code? Thanks.

**Comment by ChenWang8750** [comment]
Thanks for the excellent work! When will the Motion-X data be released?

**Comment by ailingzengzzz** [comment]
Hi @liqimai ,

We release the data via email. Please have a check!

**Comment by liqimai** [comment]
Thanks a lot! I received it!
