### ISSUE TITLE
When will you release  'whole-body pose descriptions'?

### ISSUE THREAD

**Issue by blue-blue272** [IDEA-Research/Motion-X#41]
It is a wonderful work. I wonder when will you release  **whole-body pose descriptions**.  It is very helpful to my research. Thanks a lot!

**Comment by HiHiAllen** [comment]
Me too. Looking forward to it.

**Comment by ailingzengzzz** [comment]
Hi  @blue-blue272 @HiHiAllen ,

We update the frame-level textual descriptions for each whole-body pose. Please download it [here](https://drive.google.com/file/d/168ja-oBTHM0QDKFIcRriQFPew5gUlZkQ/view?usp=sharing) and refer to this usage guidance[PoseTEXT_README](https://github.com/IDEA-Research/Motion-X/blob/main/PoseText/PoseText_README.md).

**Comment by HiHiAllen** [comment]
@ailingzengzzz Very inspiring, thank you for your contribution!

**Comment by HiHiAllen** [comment]
@ailingzengzzz   I'd like to extract pose descriptions of some other images, is it possible to release pipeline codebase?

**Comment by ailingzengzzz** [comment]
Hi @HiHiAllen,

Yes, we plan to release the code of whole-body text descriptions soon.

**Comment by HiHiAllen** [comment]
@ailingzengzzz  That's great! Looking forward to it.
