### ISSUE TITLE
Duplicated GRAB datasets in mocap-data-processing

### ISSUE THREAD

**Issue by hdjsjyl** [IDEA-Research/Motion-X#44]
Hi Author,
    Thanks for your excellent work.
    I found there are a duplicated data in mocap-data.
    GRAB datasets exists in the amass data. And also, in the mocap-data-processing needs to download GRAB alone. 
    Are these two GRAB datasets same? Thanks

**Comment by hdjsjyl** [comment]
Hi @shunlinlu , double check, these two GRAB are different, right? thx

**Comment by shunlinlu** [comment]
Hi, @hdjsjyl 

I check these two versions. The body_pose and hand_pose are slightly different. We use the GRAB from [here](https://grab.is.tue.mpg.de/). I believe it is okay to use GRAB from AMASS and you may need to rewrite the processing script.

Shunlin

**Comment by hdjsjyl** [comment]
Hi @shunlinlu , thanks for your reply. 
In terms of the readme. 
![image](https://github.com/IDEA-Research/Motion-X/assets/7590139/cda27178-34bf-440f-a2e1-894c11d7025b)
![image](https://github.com/IDEA-Research/Motion-X/assets/7590139/3a0be6d9-4cc9-4c1d-8e2c-b78f112794fc)
While downloading AMASS, it includes a subset of GRAB. After that, the readme shows that we need to download another GRAB dataset. I just want to double check they are different to make sure the readme is correct. 

Like what you said, if I used the GRAM from AMASS, we need to rewrite the processing script. But the readme doesn't show the processing script. thanks

**Comment by shunlinlu** [comment]
Hi, @hdjsjyl 

Sorry for the ambiguous expressions. I've updated the readme. For the scripts, you may check [humanml_script](https://github.com/IDEA-Research/Motion-X/blob/main/mocap-dataset-process/humanml.py) and [Grab_script](https://github.com/IDEA-Research/Motion-X/blob/main/mocap-dataset-process/grab.py)

Shunlin

**Comment by hdjsjyl** [comment]
hi @shunlinlu ， thanks for your reply. Will check the readme.
