### ISSUE TITLE
[Bug] wrong processing for text labels for EgoBody dataset

### ISSUE THREAD

**Issue by hdjsjyl** [IDEA-Research/Motion-X#45]
![image](https://github.com/IDEA-Research/Motion-X/assets/7590139/463b7de9-f3cb-4136-8526-ad798f7335db)

Hi Author,
    I think aist.py is for non-mocap-data-process. Pls update this command, thanks

**Comment by shunlinlu** [comment]
Hi, @hdjsjyl 

Thanks for pointing out. The readme is updated. 

Shulin
