### ISSUE TITLE
A Question on transfer_to_body_only_humanml.py

### ISSUE THREAD

**Issue by OrigamiStationery** [IDEA-Research/Motion-X#48]
Thank you for your priceless work. It really helps a lot.
It seems that a motion-X data sequence is represented as a (nframes,322) vector.But in transfer_to_body_only_humanml.py it says
` data_263 = np.concatenate((data[:, :4+(body_joints - 1)*3], data[:, 4+(joints - 1)*3:4+(joints - 1)*3+(body_joints - 1)*6], data[:, 4 + (joints - 1)*9: 4 + (joints - 1) *9 + body_joints *3], data[:, -4:]), axis=1)`
with the variable joints=52, and the index 4+(joints-1)*9 is obviously bigger than 322,which causes an AssertionError in
`assert data_263.shape[1] == 263`
I failed to figure out this problem and is now dying for your assistance.OTZ
btw,express my sincere gratitude again.

**Comment by shunlinlu** [comment]
Hi, @OrigamiStationery 

Thanks for your interest! 

This script is for Tomato representation to humanml representation. So the input is represented as (nframes, 623). If you want to get humanml representation, you may first transform the data from smplx format (nframes, 322) to Tomato representation(nframes, 623). And then transfer to humanml format. Or, after running our [raw_pose_processing.py](https://github.com/IDEA-Research/Motion-X/blob/main/tomato_represenation/raw_pose_processing.py), you can use the [humanml representation preprocess code ](https://github.com/EricGuo5513/HumanML3D/blob/main/motion_representation.ipynb). 

Shunlin
