### ISSUE TITLE
Mismatch of motion and text for humaml dataset

### ISSUE THREAD

**Issue by hdjsjyl** [IDEA-Research/Motion-X#49]
Hi Author,
    After running humanml.py, the motion data .npy has no corresponding txt file. In total, there are 26292 mismatched files. And Do you have statistics for how many files for each subset? Thanks

**Comment by shunlinlu** [comment]
Hi, @hdjsjyl 

You may download the text from [humanml](https://github.com/EricGuo5513/HumanML3D/blob/main/HumanML3D/texts.zip). 

Shunlin

**Comment by hdjsjyl** [comment]
Hi @shunlinlu ,
    Thanks for your reply. I got it. Thanks
