### ISSUE TITLE
What would be orientation of the data and FPS

### ISSUE THREAD

**Issue by sohananisetty** [IDEA-Research/Motion-X#5]
Awesome work! I wanted to know what is the orientation of all the data? For example Z-up Y forward (AMASS) or Y-up Z-forward (AIST++). Also are all the motions sampled at the same FPS?

**Comment by linjing7** [comment]
Hi, thanks for your interest. You have unified the axis of all the subdataset and made the orientation of the first frame face Z+.

**Comment by sohananisetty** [comment]
You have mentioned downloading the AMASS dataset on our own. Do you provide preprocessing scripts to convert AMASS into your format? Or do you use it as it is? As far as I know, AMASS is not in the orientation you mentioned above.

**Comment by linjing7** [comment]
Hi, we will provide preprocessing scripts.

**Comment by sohananisetty** [comment]
In your HumanML processing script you say fps = 30 but in [humanact12 if condition](https://github.com/IDEA-Research/Motion-X/blob/03cb8877ddfaa7401fb6736ea9893c8bb3095f7d/mocap-dataset-process/humanml.py#L199) you use fps 20 which is similar to humanML3D processing.

**Comment by shunlinlu** [comment]
Thanks for pointing out this problem. Our dataset is 30 fps, this should be the bug in the processing code. Please check the latest commit of processing code.
