### ISSUE TITLE
2D whole-body

### ISSUE THREAD

**Issue by Solo4working** [IDEA-Research/Motion-X#75]
Thanks for your awesome repository! 🎉🎉

I want to use this repository to extract skeletons for an image. What should I do?

**Comment by zhangyuhong01** [comment]
Motion-X using a self-trained ViT model to extract the whole-body keypoints in coco format, you could consider using [mmpose](https://github.com/open-mmlab/mmpose),[openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) etc. to extract 2d wholebody keypoints from images in different formats.
