### ISSUE TITLE
BMLhandball 

### ISSUE THREAD

**Issue by ChangeNext** [IDEA-Research/Motion-X#8]
Thank for Huge Projects
I have one question
BMLhandball doesn't have SMPL-X G...
only have SMPL+H G

**Comment by shunlinlu** [comment]
@ChangeNext, thanks for your interest.

Please refer to the following code: [here](https://github.com/IDEA-Research/Motion-X/blob/78ca93cb47eaa3fa786bca15e3ce2a51d5beb452/mocap-dataset-process/humanml.py#L193). We actually ignore these datasets, as there is no SMPL-X G.

**Comment by shunlinlu** [comment]
@ChangeNext,

We have implemented VQ-VAE using the codebase from [T2m-GPT](https://github.com/Mael-zys/T2M-GPT). Please stay tuned for further updates, as we have integrated the implementations of MLD, T2M-GPT, and other related components into a unified codebase for our new motion generation framework called [HumanTOMATO](https://github.com/IDEA-Research/HumanTOMATO). We are in the process of preparing the release of the source code, pre-trained models, and pre-trained VQ tokens, which will be made available on the HumanTOMATO repository in the near future. Stay tuned for more updates and resources!

**Comment by ChangeNext** [comment]
Thank you for reply
An error occurred while running the GRAP.py file.

  File "grab.py", line 99, in <module>
    data = {k: data[k].item() for k in data.files}
  File "grab.py", line 99, in <dictcomp>
    data = {k: data[k].item() for k in data.files}
AttributeError: 'bytes' object has no attribute 'item'

I download GRAB papameter s1~s10 but error occurred
Why am I getting these errors?

**Comment by shunlinlu** [comment]
Hi, @ChangeNext 

What's your format of the grab dataset? It should be npz files. You can use np.load to load the npz, and data.files to check the keys of the data.

**Comment by ChangeNext** [comment]
Yes, grab dataset format is npz.  and I check the key of grab data is {'framerate', 'contact', 'n_frames', 'object', 'obj_name', 'lhand', 'sbj_id', 'gender', 'motion_intent', 'rhand', 'n_comps', 'table', 'body'}
but same error is occured.

**Comment by ChangeNext** [comment]
I'm sorry, my mistake. Thank you!!
