### ISSUE TITLE
Asking for the render code

### ISSUE THREAD

**Issue by zjt000125** [IDEA-Research/Motion-X#85]
Could you please provide the rendering code for the .json files in mesh_recovery directory? I found the rendering results to be strange when using the camera pose from the .json files.

**Comment by zjt000125** [comment]
![image (6)](https://github.com/IDEA-Research/Motion-X/assets/142747058/688b93fb-6755-4e10-840f-6dd3346d81e4)
The mesh converted from smplx parameter is good, but the rendered normal map using the given camera pose is weird.
![image (7)](https://github.com/IDEA-Research/Motion-X/assets/142747058/983dabbc-54ce-4a33-8450-488106f08d7d)
Looks like the camera is too close to the mesh.

**Comment by zhangyuhong01** [comment]
Hi~ We have provided code related to camera projection methods and [visualization,](https://github.com/IDEA-Research/Motion-X/tree/main/visualization) which can be used to project correctly using the camera poses and motions we provide, I hope it will help you.

**Comment by rheallyc** [comment]
> Hi~ We have provided code related to camera projection methods and [visualization,](https://github.com/IDEA-Research/Motion-X/tree/main/visualization) which can be used to project correctly using the camera poses and motions we provide, I hope it will help you.

hi! may I ask where is "utils.human_models" referring to in line 37 of 'render_camera_space_motion.py'?
