### ISSUE TITLE
Inconsistency between the frame count of humanml.py and face_motion_augmentation.py

### ISSUE THREAD

**Issue by JYuhao88** [IDEA-Research/Motion-X#9]
Could you provide the output information from humanml.py? When running face_motion_augmentation.py, I noticed a mismatch between the number of frames in the output from humanml.py and the number of frames in the face_motion data.

**Comment by JYuhao88** [comment]
I guess #5 also relates to this bug.

**Comment by sohananisetty** [comment]
This might not be a fps issue. For example, 000000.npy has 175 frames at 30fps and about 116 frames at 20fps but the face motion data has only 97 frames. The other motions follow a similar trend.

**Comment by sohananisetty** [comment]
GRAB face motion augmentation is at 20fps while motion_data is at 30 fps. Egobody seems to be fine

**Comment by linjing7** [comment]
Hi, thanks for your interest! This is indeed caused by the frame rate mismatching bug. I will fix the bug and update the code later.

**Comment by JYuhao88** [comment]
> Hi, we have fixed the bug. Please pull the latest code and then run the face motion augmentation again.

Thanks for the assistance！
