### ISSUE TITLE
About AIST++ dataset split strategy

### ISSUE THREAD

**Issue by ZeyuLing** [IDEA-Research/Motion-X#94]
Thanks for your contribution to HMS field! I would like to know how you segmented the AIST++ dataset into approximately 5-second segments. I want to do the same for the audio in AIST++. Will your share the segment code or some related paramters?(Like window size or stride, etc)

**Comment by zhangyuhong01** [comment]
You might want to refer to this code [https://github.com/Stanford-TML/EDGE/blob/main/data/slice.py](url), there should be the code you need.
